#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1662261819                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://kidylee.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Do more with less.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : An Li                                
your_link                                 : https://kidylee.com                     
your_city                                 : Earth                                
email_address                             : kidylee@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : kidylee
github_username                           : kidylee
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features:
  - title: "App Blocking"
    description: "Block distracting apps on demand to help you focus on your work."
    fontawesome_icon_name: "ban"

  - title: "Customizable Block List"
    description: "Create a personalized list of apps to block during work sessions."
    fontawesome_icon_name: "cog"

  - title: "Deep Work Mode"
    description: "Activate Deep Work mode to create a distraction-free work environment."
    fontawesome_icon_name: "moon"

  - title: "Timer"
    description: "Manage your work sessions with a built-in timer feature."
    fontawesome_icon_name: "clock"

  - title: "Productivity Stats"
    description: "Track your progress with productivity statistics on app usage."
    fontawesome_icon_name: "chart-bar"

  - title: "Easy to Use"
    description: "User-friendly interface for a seamless work experience."
    fontawesome_icon_name: "thumbs-up"

  - title: "Siri Integration"
    description: "Start and stop work sessions with voice commands using Siri."
    fontawesome_icon_name: "microphone"



# Theme Settings
topbar_color: "#262626"
topbar_transparency: 0.9
topbar_title_color: "#FFFFFF"

cover_image: assets/headerimage.png
cover_overlay_color: "#1C1C1E"
cover_overlay_transparency: 0.8

device_color: black

body_background_color: "#1C1C1E"

link_color: "#3F9DF2"

app_title_color: "#FFFFFF"
app_price_color: "#FFFFFF"
app_description_color: "#BDBDBD"

feature_title_color: "#FFFFFF"
feature_text_color: "#BDBDBD"

feature_icons_foreground_color: "#3F9DF2"
feature_icons_background_color: "#353535"

social_icons_foreground_color: "#BDBDBD"
social_icons_background_color: "#353535"

footer_text_color: "#BDBDBD"














####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
